server:
  port: 8085

spring:
  application:
    name: profile-service-grpc
  output:
    ansi.enabled: always

management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: metrics

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: 'localhost'
